name: busbay
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  google_maps_flutter: ^0.5.28+1
  location: ^3.0.2
  email_validator: ^1.0.4
  fluttertoast: ^3.1.3
  dropdownfield: 1.0.0

  
  flutter:
    sdk: flutter

  geolocator: ^5.3.1
  flutter_speed_dial: ^1.2.5
  firebase_core: "0.5.0"
  cloud_firestore: ^0.14.0+2
  firebase_auth: ^0.18.0+1
  google_sign_in: 4.5.4
  rxdart: 0.20.0
  provider: ^4.3.2+2
  get_it: ^4.0.1
  font_awesome_flutter: ^8.10.0
  percent_indicator: ^2.1.8
  flutter_icons: ^1.1.0
  flushbar: ^1.10.4
  firebase_messaging:
  flutter_polyline_points: ^0.2.1




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  keyboard_visibility: ^0.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets: 
      - assets/icons/
      - assets/images/


  fonts:
    - family: Montserrat
      fonts:
         - asset: assets/fo/Montserrat-Bold.ttf

    - family: NiseBuschGardens
      fonts:
        - asset: assets/fo/NiseBuschGardens.ttf

    - family: DancingScript
      fonts:
        - asset: assets/fo/DancingScript-Bold.ttf

    - family: Courgette
      fonts:
        - asset: assets/fo/NerkoOne-Regular.ttf

    - family: PermMarker
      fonts:
        - asset: assets/fo/DoHyeon-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
